name = "proveloce-backend-proxy"
main = "worker.ts"
compatibility_date = "2024-01-01"

routes = [
  { pattern = "backend.proveloce.com/*", zone_name = "proveloce.com" }
]

# ======================= D1 DATABASE BINDING =======================
d1_databases = [
  { binding = "proveloce_db", database_name = "proveloce_db", database_id = "3b3261c1-a83c-49dc-82df-4688cbdc785c" }
]

# Environment Variables
[vars]
GOOGLE_CLIENT_ID = "707765451928-ui139ks51aht4jr7fk5abh9v58gphr0l.apps.googleusercontent.com"
GOOGLE_CLIENT_SECRET = "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"
JWT_SECRET = "557ca0e6eb333ea35114e05c6545e945bd6849eb02bd9612061973bdc458993a4f4556b5e9ace05f5311056a598657b06721decc9fa8766f90331244c0e038e1"
FRONTEND_URL = "https://app.proveloce.com"
GOOGLE_CALLBACK_URL = "https://backend.proveloce.com/api/auth/google/callback"