name = "proveloce-backend-proxy"
main = "worker.ts"
compatibility_date = "2024-01-01"

# Custom domain routing
routes = [
  { pattern = "backend.proveloce.com/*", zone_name = "proveloce.com" }
]

# Optional: Add environment variables if needed
# [vars]
# RENDER_API = "https://app-0zrq.onrender.com"

[vars]
GOOGLE_CLIENT_ID = "707765451928-ui139ks51aht4jr7fk5abh9v58gphr0l.apps.googleusercontent.com"
GOOGLE_CLIENT_SECRET = "YjLuoh1KSvo6uMhkfutsOO1MyZXG"
